# Site settings
title: Be funky
email: dt0xff@gmail.com
author: Denis Tom
description: "A simple, beautiful theme for Jekyll that emphasizes content rather than aesthetic fluff."
baseurl: ""
url: "http://ohmy.rocks"

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
gems:
  - jekyll-sitemap


oold:
    author :
      name : DenisT
      email : dt0xff@gmail.com
      github : iorlas
      twitter : username
      feedburner : feedname

    # Short description (will also be used in the RSS feed)
    description: 'Thoughts, ideas and experiance of stupid developer'

    # Continue compiling even if there are errors. Keep it true, unless troubleshooting.
    #auto: true

    # Makes pretty permalinks. See Jekyll docs for alternatives.
    permalink: pretty
    pygments: true
    markdown: rdiscount

    disqus_name: iorlasblog
    google-analytics-id: 'UA-36442381-2'
    google-custom-search-id: '012092466656707447144:lmaxqxu7fjm'
    production_url: http://iorlas.com
