# Name of your blog (this will show up in the RSS feed)
name: Socially Awkward Penguin blog

author :
  name : DenisT
  email : dt0xff@gmail.com
  github : iorlas
  twitter : username
  feedburner : feedname

# Short description (will also be used in the RSS feed)
description: 'Thoughts, ideas and experiance of stupid developer'

# Continue compiling even if there are errors. Keep it true, unless troubleshooting.
#auto: true

# Makes pretty permalinks. See Jekyll docs for alternatives.
permalink: pretty
pygments: true
markdown: rdiscount

disqus_name: iorlasblog
google-analytics-id: 'UA-36442381-2'
google-custom-search-id: '012092466656707447144:lmaxqxu7fjm'
production_url: http://iorlas.com